# Generated by Django 5.0.14 on 2026-07-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or description of the PDF document', max_length=255)),
                ('pdf_file', models.FileField(help_text='Upload PDF file to index for RAG', upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Status indicating whether PDF was indexed into ChromaDB')),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of vector text chunks stored in ChromaDB')),
            ],
            options={
                'verbose_name': 'PDF Document (RAG Knowledge)',
                'verbose_name_plural': 'PDF Documents (RAG Knowledge)',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
