# Generated by Django 5.0.14 on 2026-07-27 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company or Business Name', max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL friendly identifier', max_length=255, unique=True)),
                ('api_key', models.CharField(blank=True, help_text='API Key for widget integration', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active tenant status')),
            ],
            options={
                'verbose_name': 'Company (Tenant)',
                'verbose_name_plural': 'Companies (Tenants)',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company (Tenant) owning this document', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to='chatbot.company'),
        ),
    ]
